"""
Health Risk Predictor Service

This is a PROTOTYPE AI model for preliminary health risk assessment.
It is NOT a medical diagnostic tool.

The model uses a combination of:
1. Rule-based vital sign analysis
2. Symptom pattern matching
3. Machine learning risk scoring (Random Forest)
"""

import os
import joblib
import numpy as np
import pandas as pd
from typing import Dict, List, Optional, Any

# Disclaimer that must be included with all predictions
DISCLAIMER = """This is an AI-assisted preliminary risk assessment and is NOT a medical diagnosis. 
The results are generated by a machine learning model trained on health data patterns and should be used 
for informational purposes only. Please consult a qualified healthcare professional for proper medical 
evaluation and advice. In case of emergency, contact emergency services immediately."""

MODEL_VERSION = "1.0.0-prototype"

# Supported symptoms for the model
SUPPORTED_SYMPTOMS = [
    "Fever", "Cough", "Cold", "Headache", "Body Pain", "Fatigue",
    "Nausea", "Vomiting", "Diarrhea", "Chest Pain", "Shortness of Breath",
    "Dizziness", "Loss of Appetite", "Sore Throat", "Runny Nose",
    "Joint Pain", "Muscle Pain", "Abdominal Pain", "Back Pain",
    "Skin Rash", "Swelling", "Weakness", "Weight Loss",
    "Difficulty Sleeping", "Anxiety", "Palpitations", "Excessive Thirst",
    "Frequent Urination", "Blurred Vision", "Numbness", "Tingling"
]

SYMPTOM_CATEGORIES = {
    "Respiratory": ["Cough", "Cold", "Shortness of Breath", "Sore Throat", "Runny Nose"],
    "Cardiovascular": ["Chest Pain", "Palpitations", "Swelling", "Shortness of Breath"],
    "Gastrointestinal": ["Nausea", "Vomiting", "Diarrhea", "Abdominal Pain", "Loss of Appetite"],
    "Neurological": ["Headache", "Dizziness", "Numbness", "Tingling", "Blurred Vision"],
    "Musculoskeletal": ["Body Pain", "Joint Pain", "Muscle Pain", "Back Pain", "Weakness"],
    "General": ["Fever", "Fatigue", "Weight Loss", "Skin Rash", "Difficulty Sleeping"],
    "Diabetes Indicators": ["Excessive Thirst", "Frequent Urination", "Blurred Vision", "Fatigue"]
}

# Vital sign normal ranges
VITAL_RANGES = {
    "heartRate": {"min": 60, "max": 100, "critical_low": 40, "critical_high": 150},
    "systolic": {"min": 90, "max": 120, "critical_low": 70, "critical_high": 180},
    "diastolic": {"min": 60, "max": 80, "critical_low": 40, "critical_high": 120},
    "temperature": {"min": 97, "max": 99, "critical_low": 95, "critical_high": 104},
    "spo2": {"min": 95, "max": 100, "critical_low": 90, "critical_high": None},
    "glucose": {"min": 70, "max": 140, "critical_low": 50, "critical_high": 400}
}

class HealthRiskPredictor:
    def __init__(self):
        self.model = None
        self.model_loaded = False
        self._load_model()
    
    def _load_model(self):
        """Load the trained model if it exists, otherwise use rule-based system."""
        model_path = os.path.join(os.path.dirname(__file__), "../models/health_risk_model.pkl")
        if os.path.exists(model_path):
            try:
                self.model = joblib.load(model_path)
                self.model_loaded = True
            except Exception as e:
                print(f"Warning: Could not load model: {e}")
                self.model_loaded = False
        else:
            print("Model file not found. Using rule-based assessment.")
            self.model_loaded = False
    
    def get_supported_symptoms(self) -> List[str]:
        """Return list of supported symptoms."""
        return SUPPORTED_SYMPTOMS
    
    def get_symptom_categories(self) -> Dict[str, List[str]]:
        """Return symptom categories."""
        return SYMPTOM_CATEGORIES
    
    def _analyze_vitals(self, vitals: Dict[str, Any]) -> tuple[List[Dict], float]:
        """
        Analyze vital signs and return indicators with risk contribution.
        """
        indicators = []
        risk_score = 0.0
        vital_count = 0
        
        # Heart Rate
        if vitals.get("heartRate"):
            hr = vitals["heartRate"]
            vital_count += 1
            range_info = VITAL_RANGES["heartRate"]
            
            if hr < range_info["critical_low"] or hr > range_info["critical_high"]:
                indicators.append({
                    "name": "Heart Rate",
                    "status": "critical",
                    "value": f"{hr} bpm",
                    "message": f"Heart rate is critically {'low' if hr < 60 else 'high'}. Seek immediate medical attention."
                })
                risk_score += 0.4
            elif hr < range_info["min"] or hr > range_info["max"]:
                indicators.append({
                    "name": "Heart Rate",
                    "status": "abnormal",
                    "value": f"{hr} bpm",
                    "message": f"Heart rate is {'below' if hr < 60 else 'above'} normal range."
                })
                risk_score += 0.2
            else:
                indicators.append({
                    "name": "Heart Rate",
                    "status": "normal",
                    "value": f"{hr} bpm"
                })
        
        # Blood Pressure
        if vitals.get("bloodPressure"):
            bp = vitals["bloodPressure"]
            sys = bp.get("systolic")
            dia = bp.get("diastolic")
            
            if sys and dia:
                vital_count += 1
                sys_range = VITAL_RANGES["systolic"]
                dia_range = VITAL_RANGES["diastolic"]
                
                is_critical = (sys > sys_range["critical_high"] or sys < sys_range["critical_low"] or
                              dia > dia_range["critical_high"] or dia < dia_range["critical_low"])
                is_abnormal = (sys > sys_range["max"] or sys < sys_range["min"] or
                              dia > dia_range["max"] or dia < dia_range["min"])
                
                if is_critical:
                    indicators.append({
                        "name": "Blood Pressure",
                        "status": "critical",
                        "value": f"{sys}/{dia} mmHg",
                        "message": "Blood pressure is at a critical level. Seek immediate medical attention."
                    })
                    risk_score += 0.4
                elif is_abnormal:
                    indicators.append({
                        "name": "Blood Pressure",
                        "status": "abnormal",
                        "value": f"{sys}/{dia} mmHg",
                        "message": "Blood pressure is outside normal range."
                    })
                    risk_score += 0.2
                else:
                    indicators.append({
                        "name": "Blood Pressure",
                        "status": "normal",
                        "value": f"{sys}/{dia} mmHg"
                    })
        
        # Temperature
        if vitals.get("temperature"):
            temp = vitals["temperature"]
            vital_count += 1
            range_info = VITAL_RANGES["temperature"]
            
            if temp < range_info["critical_low"] or temp > range_info["critical_high"]:
                indicators.append({
                    "name": "Temperature",
                    "status": "critical",
                    "value": f"{temp}°F",
                    "message": f"Temperature is critically {'low (hypothermia)' if temp < 95 else 'high (hyperthermia)'}."
                })
                risk_score += 0.35
            elif temp < range_info["min"] or temp > range_info["max"]:
                indicators.append({
                    "name": "Temperature",
                    "status": "abnormal",
                    "value": f"{temp}°F",
                    "message": f"{'Low-grade' if temp < 100 else 'Elevated'} temperature detected."
                })
                risk_score += 0.15
            else:
                indicators.append({
                    "name": "Temperature",
                    "status": "normal",
                    "value": f"{temp}°F"
                })
        
        # SpO2
        if vitals.get("spo2"):
            spo2 = vitals["spo2"]
            vital_count += 1
            range_info = VITAL_RANGES["spo2"]
            
            if spo2 < range_info["critical_low"]:
                indicators.append({
                    "name": "Oxygen Saturation",
                    "status": "critical",
                    "value": f"{spo2}%",
                    "message": "Oxygen level is dangerously low. Seek immediate medical attention."
                })
                risk_score += 0.5
            elif spo2 < range_info["min"]:
                indicators.append({
                    "name": "Oxygen Saturation",
                    "status": "abnormal",
                    "value": f"{spo2}%",
                    "message": "Oxygen level is below normal. Monitor closely."
                })
                risk_score += 0.25
            else:
                indicators.append({
                    "name": "Oxygen Saturation",
                    "status": "normal",
                    "value": f"{spo2}%"
                })
        
        # Blood Glucose
        if vitals.get("glucose"):
            glucose = vitals["glucose"]
            vital_count += 1
            range_info = VITAL_RANGES["glucose"]
            
            if glucose < range_info["critical_low"] or glucose > range_info["critical_high"]:
                indicators.append({
                    "name": "Blood Glucose",
                    "status": "critical",
                    "value": f"{glucose} mg/dL",
                    "message": f"Blood glucose is critically {'low (hypoglycemia)' if glucose < 70 else 'high (hyperglycemia)'}."
                })
                risk_score += 0.35
            elif glucose < range_info["min"] or glucose > range_info["max"]:
                indicators.append({
                    "name": "Blood Glucose",
                    "status": "abnormal",
                    "value": f"{glucose} mg/dL",
                    "message": f"Blood glucose is {'below' if glucose < 70 else 'above'} normal range."
                })
                risk_score += 0.15
            else:
                indicators.append({
                    "name": "Blood Glucose",
                    "status": "normal",
                    "value": f"{glucose} mg/dL"
                })
        
        return indicators, risk_score
    
    def _analyze_symptoms(self, symptoms: List[str]) -> tuple[List[Dict], float]:
        """
        Analyze symptoms and return indicators with risk contribution.
        """
        indicators = []
        risk_score = 0.0
        
        # Count symptoms by category
        symptom_set = set(s.lower() for s in symptoms)
        
        # High-risk symptoms
        high_risk_symptoms = {"chest pain", "shortness of breath", "severe headache", "numbness", "blurred vision"}
        high_risk_found = symptom_set.intersection(high_risk_symptoms)
        
        if high_risk_found:
            indicators.append({
                "name": "Concerning Symptoms",
                "status": "critical",
                "value": ", ".join(high_risk_found),
                "message": "These symptoms require prompt medical evaluation."
            })
            risk_score += 0.3
        
        # Symptom count
        symptom_count = len(symptoms)
        if symptom_count >= 5:
            risk_score += 0.2
        elif symptom_count >= 3:
            risk_score += 0.1
        
        # Add symptom summary indicator
        if symptom_count > 0:
            indicators.append({
                "name": "Symptoms Reported",
                "status": "abnormal" if symptom_count >= 3 else "normal",
                "value": str(symptom_count),
                "message": f"{symptom_count} symptom(s) reported for assessment."
            })
        
        return indicators, risk_score
    
    def _calculate_risk_from_history(self, medical_history: List[str]) -> float:
        """Calculate additional risk based on medical history."""
        high_risk_conditions = {
            "diabetes", "hypertension", "heart disease", "kidney disease",
            "asthma", "copd", "cancer", "hiv", "tuberculosis"
        }
        
        history_set = set(h.lower() for h in medical_history)
        matches = history_set.intersection(high_risk_conditions)
        
        return min(0.2, len(matches) * 0.05)
    
    def _determine_risk_level(self, risk_score: float) -> str:
        """Determine risk level from score."""
        if risk_score >= 0.6:
            return "HIGH"
        elif risk_score >= 0.3:
            return "MODERATE"
        else:
            return "LOW"
    
    def _generate_recommendation(self, risk_level: str, indicators: List[Dict]) -> str:
        """Generate recommendation based on risk assessment."""
        critical_count = sum(1 for i in indicators if i.get("status") == "critical")
        
        if risk_level == "HIGH" or critical_count > 0:
            return ("Based on the symptoms and vitals provided, this assessment indicates elevated health risk. "
                   "Professional medical evaluation is strongly recommended. Please consult a healthcare "
                   "professional at the earliest opportunity or visit a nearby healthcare facility.")
        elif risk_level == "MODERATE":
            return ("This assessment indicates some health concerns that warrant attention. "
                   "Consider scheduling a consultation with a healthcare professional "
                   "to discuss your symptoms and get proper evaluation.")
        else:
            return ("Based on the current assessment, no immediate health concerns are indicated. "
                   "Continue monitoring your health and maintain regular check-ups. "
                   "If symptoms persist or worsen, please consult a healthcare professional.")

    def _predict_ml(
        self,
        age: int,
        gender: str,
        symptoms: List[str],
        vitals: Dict[str, Any],
        medical_history: List[str]
    ) -> Dict[str, Any]:
        """
        Execute statistical ML inference using trained ensemble model.
        """
        feature_cols = self.model.get("feature_columns", [])
        risk_clf = self.model.get("risk_classifier")
        cond_clf = self.model.get("condition_classifier")

        # Build feature vector
        row = {col: 0 for col in feature_cols}
        row["age"] = age
        row["gender_M"] = 1 if gender.upper() == "M" else 0
        row["gender_F"] = 1 if gender.upper() == "F" else 0

        # Medical history flags
        history_lower = [h.lower() for h in medical_history]
        row["history_diabetes"] = 1 if any("diabet" in h for h in history_lower) else 0
        row["history_hypertension"] = 1 if any("hyper" in h or "bp" in h for h in history_lower) else 0
        row["history_asthma"] = 1 if any("asthma" in h or "breath" in h for h in history_lower) else 0

        # Vitals extraction
        row["vital_heart_rate"] = vitals.get("heartRate") or 75
        bp = vitals.get("bloodPressure") or {}
        row["vital_systolic_bp"] = bp.get("systolic") if bp else (vitals.get("systolic") or 120)
        row["vital_diastolic_bp"] = bp.get("diastolic") if bp else (vitals.get("diastolic") or 80)
        row["vital_temperature"] = vitals.get("temperature") or 98.6
        row["vital_spo2"] = vitals.get("spo2") or 98
        row["vital_glucose"] = vitals.get("glucose") or 100

        # Symptoms mapping
        symptoms_clean = [s.strip().lower() for s in symptoms]
        for s in symptoms_clean:
            col_name = f"symptom_{s}"
            if col_name in row:
                row[col_name] = 1

        df_input = pd.DataFrame([row])[feature_cols]

        # 1. Risk Prediction & Class Probabilities
        risk_classes = list(risk_clf.classes_)
        risk_probs = risk_clf.predict_proba(df_input)[0]
        prob_dict = dict(zip(risk_classes, risk_probs))
        pred_risk_level = risk_clf.predict(df_input)[0]

        # Continuous risk score (0.0 to 1.0)
        prob_high = prob_dict.get("HIGH", 0.0)
        prob_mod = prob_dict.get("MODERATE", 0.0)
        prob_low = prob_dict.get("LOW", 0.0)
        risk_score = round(float(prob_high * 0.95 + prob_mod * 0.55 + prob_low * 0.10), 2)

        # 2. Predicted Conditions with Confidence Scores
        possible_conditions = []
        if cond_clf:
            cond_classes = list(cond_clf.classes_)
            cond_probs = cond_clf.predict_proba(df_input)[0]
            sorted_indices = np.argsort(cond_probs)[::-1][:3]
            for idx in sorted_indices:
                if cond_probs[idx] > 0.08:
                    possible_conditions.append({
                        "condition": cond_classes[idx],
                        "confidence": round(float(cond_probs[idx]), 3)
                    })

        # 3. Clinical Indicators
        vital_indicators, _ = self._analyze_vitals(vitals)
        symptom_indicators, _ = self._analyze_symptoms(symptoms)
        all_indicators = vital_indicators + symptom_indicators

        recommendation = self._generate_recommendation(pred_risk_level, all_indicators)

        return {
            "riskLevel": pred_risk_level,
            "riskScore": risk_score,
            "indicators": all_indicators,
            "possibleConditions": possible_conditions,
            "probabilities": {k: round(float(v), 3) for k, v in prob_dict.items()},
            "recommendation": recommendation,
            "disclaimer": DISCLAIMER,
            "modelVersion": self.model.get("model_version", "2.0.0-ml-ensemble")
        }

    def predict(
        self,
        age: int,
        gender: str,
        symptoms: List[str],
        vitals: Dict[str, Any],
        medical_history: List[str]
    ) -> Dict[str, Any]:
        """
        Perform health risk assessment.
        Uses trained ML ensemble model if available, otherwise rule-based fallback.
        THIS IS NOT A MEDICAL DIAGNOSIS.
        """
        # Statistical ML inference
        if self.model_loaded and isinstance(self.model, dict) and "risk_classifier" in self.model:
            return self._predict_ml(age, gender, symptoms, vitals, medical_history)

        # Rule-based fallback
        all_indicators = []
        total_risk = 0.0
        
        # Analyze vitals
        vital_indicators, vital_risk = self._analyze_vitals(vitals)
        all_indicators.extend(vital_indicators)
        total_risk += vital_risk
        
        # Analyze symptoms
        symptom_indicators, symptom_risk = self._analyze_symptoms(symptoms)
        all_indicators.extend(symptom_indicators)
        total_risk += symptom_risk
        
        # Factor in medical history
        history_risk = self._calculate_risk_from_history(medical_history)
        total_risk += history_risk
        
        # Age factor (elderly and very young have higher risk)
        if age > 60 or age < 5:
            total_risk += 0.1
        
        # Cap risk score at 1.0
        total_risk = min(1.0, total_risk)
        
        # Determine risk level
        risk_level = self._determine_risk_level(total_risk)
        
        # Generate recommendation
        recommendation = self._generate_recommendation(risk_level, all_indicators)
        
        return {
            "riskLevel": risk_level,
            "riskScore": round(total_risk, 2),
            "indicators": all_indicators,
            "recommendation": recommendation,
            "disclaimer": DISCLAIMER,
            "modelVersion": MODEL_VERSION
        }
    
    def analyze_symptoms(self, symptoms: List[str]) -> Dict[str, Any]:
        """
        Quick symptom analysis without vitals.
        """
        indicators, risk_score = self._analyze_symptoms(symptoms)
        risk_level = self._determine_risk_level(risk_score)
        
        return {
            "riskLevel": risk_level,
            "riskScore": round(risk_score, 2),
            "symptoms": symptoms,
            "possibleCategories": self._categorize_symptoms(symptoms),
            "recommendation": "Please provide vital signs for a more comprehensive assessment.",
            "disclaimer": DISCLAIMER,
            "modelVersion": MODEL_VERSION
        }
    
    def _categorize_symptoms(self, symptoms: List[str]) -> List[str]:
        """Categorize symptoms into health areas."""
        categories = set()
        symptom_set = set(s.lower() for s in symptoms)
        
        for category, category_symptoms in SYMPTOM_CATEGORIES.items():
            category_symptom_set = set(s.lower() for s in category_symptoms)
            if symptom_set.intersection(category_symptom_set):
                categories.add(category)
        
        return list(categories)
