import { ReactNode } from 'react'
import { AlertCircle, CheckCircle, AlertTriangle, Info, X } from 'lucide-react'

type AlertVariant = 'success' | 'warning' | 'error' | 'info'

interface AlertProps {
  variant?: AlertVariant
  title?: string
  children: ReactNode
  className?: string
  onClose?: () => void
  icon?: ReactNode
}

function Alert({
  variant = 'info',
  title,
  children,
  className = '',
  onClose,
  icon,
}: AlertProps) {
  const icons = {
    success: <CheckCircle className="w-5 h-5" />,
    warning: <AlertTriangle className="w-5 h-5" />,
    error: <AlertCircle className="w-5 h-5" />,
    info: <Info className="w-5 h-5" />,
  }

  const styles = {
    success: {
      bg: 'bg-green-50',
      border: 'border-green-200',
      text: 'text-green-800',
      icon: 'text-green-500',
    },
    warning: {
      bg: 'bg-yellow-50',
      border: 'border-yellow-200',
      text: 'text-yellow-800',
      icon: 'text-yellow-500',
    },
    error: {
      bg: 'bg-red-50',
      border: 'border-red-200',
      text: 'text-red-800',
      icon: 'text-red-500',
    },
    info: {
      bg: 'bg-blue-50',
      border: 'border-blue-200',
      text: 'text-blue-800',
      icon: 'text-blue-500',
    },
  }

  const style = styles[variant]

  return (
    <div
      className={`
        flex gap-3 p-4 rounded-lg border
        ${style.bg} ${style.border}
        ${className}
      `}
      role="alert"
    >
      <div className={`flex-shrink-0 ${style.icon}`}>
        {icon || icons[variant]}
      </div>
      <div className="flex-1">
        {title && (
          <h4 className={`text-sm font-medium ${style.text}`}>{title}</h4>
        )}
        <div className={`text-sm ${style.text} ${title ? 'mt-1' : ''}`}>
          {children}
        </div>
      </div>
      {onClose && (
        <button
          onClick={onClose}
          className={`flex-shrink-0 p-1 rounded hover:bg-gray-200/50 transition-colors ${style.text}`}
          aria-label="Dismiss"
        >
          <X className="w-4 h-4" />
        </button>
      )}
    </div>
  )
}

// AI Disclaimer Alert
function AIDisclaimerAlert({ className = '' }: { className?: string }) {
  return (
    <Alert variant="warning" title="Important Disclaimer" className={className}>
      <p>
        This is an <strong>AI-assisted preliminary risk assessment</strong> and is{' '}
        <strong>NOT a medical diagnosis</strong>. The results are generated by a machine
        learning model and should be used for informational purposes only. Please
        consult a qualified healthcare professional for proper medical evaluation
        and advice.
      </p>
    </Alert>
  )
}

// Emergency Alert
function EmergencyAlert({ className = '' }: { className?: string }) {
  return (
    <Alert variant="error" title="Emergency Notice" className={className}>
      <p>
        This application does not replace emergency medical services. In case of a
        medical emergency, please <strong>call 112</strong> or visit the nearest
        emergency room immediately.
      </p>
    </Alert>
  )
}

export { Alert, AIDisclaimerAlert, EmergencyAlert };
export default Alert;
